; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = 
	BOARD_VIEWE_UEDX48480021_MD80ET

[env]
framework = arduino
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
platform_packages = 
	platformio/framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#3.1.1
monitor_speed = 115200
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
lib_deps =
	https://github.com/esp-arduino-libs/ESP32_Display_Panel.git
	https://github.com/esp-arduino-libs/ESP32_IO_Expander.git#v1.1.0
	https://github.com/esp-arduino-libs/esp-lib-utils.git#v0.2.0
	https://github.com/lvgl/lvgl.git#v8.4.0
	https://github.com/esp-arduino-libs/ESP32_Button.git
	https://github.com/esp-arduino-libs/ESP32_Knob.git
	bblanchon/ArduinoJson@^7.4.2
	links2004/WebSockets@^2.4.1

[common]
build_flags = 
	-DCORE_DEBUG_LEVEL=1
	-DLV_CONF_INCLUDE_SIMPLE
	-DLV_LVGL_H_INCLUDE_SIMPLE
	-I src
	-I lib

[spi_qspi_lcd]
build_flags = 
	-DLV_COLOR_16_SWAP=1

[rgb_mipi_lcd]
build_flags = 
	-DLV_COLOR_16_SWAP=0

[env:BOARD_CUSTOM]
build_flags = 
	${common.build_flags}
board = BOARD_CUSTOM

[env:BOARD_VIEWE_UEDX46460015_MD50ET]
build_flags = 
	${common.build_flags}
	${rgb_mipi_lcd.build_flags}
	-DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
	-DBOARD_VIEWE_UEDX46460015_MD50ET
board = BOARD_VIEWE_UEDX46460015_MD50ET

[env:BOARD_VIEWE_UEDX48480021_MD80ET]
build_flags = 
	${common.build_flags}
	${rgb_mipi_lcd.build_flags}
	-DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
	-DBOARD_VIEWE_UEDX48480021_MD80ET
board = BOARD_VIEWE_UEDX48480021_MD80ET

[env:BOARD_VIEWE_UEDX80480050E_WB_A]
build_flags = 
	${common.build_flags}
	${rgb_mipi_lcd.build_flags}
	-DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
	-DBOARD_VIEWE_UEDX80480050E_WB_A
board = BOARD_VIEWE_UEDX80480050E_WB_A

[env:BOARD_VIEWE_UEDX80480070E_WB_A]
build_flags = 
	${common.build_flags}
	${rgb_mipi_lcd.build_flags}
	-DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
	-DBOARD_VIEWE_UEDX80480070E_WB_A
board = BOARD_VIEWE_UEDX80480070E_WB_A

[env:BOARD_ESPRESSIF_ESP32_C3_LCDKIT]
build_flags = 
	${common.build_flags}
	${spi_qspi_lcd.build_flags}
	-DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
	-DBOARD_ESPRESSIF_ESP32_C3_LCDKIT
board = BOARD_ESPRESSIF_ESP32_C3_LCDKIT

[env:BOARD_ESPRESSIF_ESP32_S3_BOX]
build_flags = 
	${common.build_flags}
	${spi_qspi_lcd.build_flags}
	-DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
	-DBOARD_ESPRESSIF_ESP32_S3_BOX
board = BOARD_ESPRESSIF_ESP32_S3_BOX

[env:BOARD_ESPRESSIF_ESP32_S3_BOX_3]
build_flags = 
	${common.build_flags}
	${spi_qspi_lcd.build_flags}
	-DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
	-DBOARD_ESPRESSIF_ESP32_S3_BOX_3
board = BOARD_ESPRESSIF_ESP32_S3_BOX_3

[env:BOARD_ESPRESSIF_ESP32_S3_EYE]
build_flags = 
	${common.build_flags}
	${spi_qspi_lcd.build_flags}
	-DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
	-DBOARD_ESPRESSIF_ESP32_S3_EYE
board = BOARD_ESPRESSIF_ESP32_S3_EYE

[env:BOARD_ESPRESSIF_ESP32_S3_KORVO_2]
build_flags = 
	${common.build_flags}
	${spi_qspi_lcd.build_flags}
	-DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
	-DBOARD_ESPRESSIF_ESP32_S3_KORVO_2
board = BOARD_ESPRESSIF_ESP32_S3_KORVO_2

[env:BOARD_ESPRESSIF_ESP32_S3_LCD_EV_BOARD]
build_flags = 
	${common.build_flags}
	${rgb_mipi_lcd.build_flags}
	-DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
	-DBOARD_ESPRESSIF_ESP32_S3_LCD_EV_BOARD
board = BOARD_ESPRESSIF_ESP32_S3_LCD_EV_BOARD

[env:BOARD_ESPRESSIF_ESP32_S3_LCD_EV_BOARD_2]
build_flags = 
	${common.build_flags}
	${rgb_mipi_lcd.build_flags}
	-DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
	-DBOARD_ESPRESSIF_ESP32_S3_LCD_EV_BOARD_2
board = BOARD_ESPRESSIF_ESP32_S3_LCD_EV_BOARD_2

[env:BOARD_ESPRESSIF_ESP32_S3_LCD_EV_BOARD_V1_5]
build_flags = 
	${common.build_flags}
	${rgb_mipi_lcd.build_flags}
	-DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
	-DBOARD_ESPRESSIF_ESP32_S3_LCD_EV_BOARD_V1_5
board = BOARD_ESPRESSIF_ESP32_S3_LCD_EV_BOARD_V1_5

[env:BOARD_ESPRESSIF_ESP32_S3_LCD_EV_BOARD_2_V1_5]
build_flags = 
	${common.build_flags}
	${rgb_mipi_lcd.build_flags}
	-DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
	-DBOARD_ESPRESSIF_ESP32_S3_LCD_EV_BOARD_2_V1_5
board = BOARD_ESPRESSIF_ESP32_S3_LCD_EV_BOARD_2_V1_5

[env:BOARD_ESPRESSIF_ESP32_S3_USB_OTG]
build_flags = 
	${common.build_flags}
	${spi_qspi_lcd.build_flags}
	-DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
	-DBOARD_ESPRESSIF_ESP32_S3_USB_OTG
board = BOARD_ESPRESSIF_ESP32_S3_USB_OTG

[env:BOARD_ESPRESSIF_ESP32_P4_FUNCTION_EV_BOARD]
build_flags = 
	${common.build_flags}
	${rgb_mipi_lcd.build_flags}
	-DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
	-DBOARD_ESPRESSIF_ESP32_P4_FUNCTION_EV_BOARD
board = BOARD_ESPRESSIF_ESP32_P4_FUNCTION_EV_BOARD
